version: '3.7'

services:
  pgdb:
    image: postgres:14
    volumes:
      - ./pgdb-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"

  himatro-web-app:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - pgdb
